
"use client";

import { Button } from "@/components/ui/button";
import { Download, History } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import JSZip from 'jszip';
import { saveAs } from 'file-saver';

interface ProjectControlsProps {
  onExport?: () => void;
  onShowHistory?: () => void;
  disableExport?: boolean;
  disableHistory?: boolean;
  filesToExport?: { path: string; content: string }[];
  projectName?: string;
}

export const ProjectControls: React.FC<ProjectControlsProps> = ({
  onExport,
  onShowHistory,
  disableExport,
  disableHistory,
  filesToExport,
  projectName = "CodeIgniterProject"
}) => {
  const { toast } = useToast();

  const handleExport = async () => {
    if (onExport) {
      onExport();
    } else if (filesToExport && filesToExport.length > 0) {
      try {
        const zip = new JSZip();
        filesToExport.forEach(file => {
          // Ensure paths are valid for ZIP (e.g., no leading slashes if not intended)
          // For nested structures, JSZip handles paths like "app/Controllers/Home.php" correctly.
          zip.file(file.path, file.content);
        });
        
        // Add a README or manifest if desired
        const readmeContent = `Generated by CodeIgniter Studio.
Project: ${projectName}
Contains the following files:
${filesToExport.map(f => `- ${f.path}`).join("\n")}

To run this CodeIgniter 4 project:
1. Ensure you have PHP and Composer installed.
2. Extract this ZIP file.
3. Navigate to the project directory in your terminal.
4. Run 'composer install' to install dependencies (if a composer.json is included and requires it).
5. If a '.env' file is present, review and update it for your environment (e.g., database credentials, app.baseURL). If there's an 'env' file, copy it to '.env'.
6. Run 'php spark migrate' to run database migrations (if migrations are included).
7. Run 'php spark serve' to start the development server.
`;
        zip.file("README_CI_STUDIO.txt", readmeContent);

        const zipFileName = `${projectName.replace(/\s+/g, '_') || 'CodeIgniterPackage'}.zip`;

        zip.generateAsync({ type: "blob" })
          .then(content => {
            saveAs(content, zipFileName);
            toast({
              title: "Package Downloaded",
              description: `Your CodeIgniter package "${zipFileName}" has been successfully downloaded.`,
            });
          })
          .catch(err => {
            console.error("Error generating ZIP:", err);
            toast({
              title: "Error Generating ZIP",
              description: "Could not generate the package .zip file. Please try again.",
              variant: "destructive",
            });
          });
      } catch (error) {
        console.error("Error during ZIP creation process:", error);
        toast({
          title: "Download Error",
          description: "An unexpected error occurred while preparing the download.",
          variant: "destructive",
        });
      }
    } else {
       toast({
        title: "Nothing to Download",
        description: "Generate or create some files first.",
        variant: "destructive"
      });
    }
  };

  return (
    <div className="flex gap-2 p-4 border-t bg-card">
      <Button onClick={handleExport} disabled={disableExport || !filesToExport || filesToExport.length === 0}>
        <Download className="mr-2 h-4 w-4" />
        Download Package
      </Button>
      {onShowHistory && (
        <Button variant="outline" onClick={onShowHistory} disabled={disableHistory}>
          <History className="mr-2 h-4 w-4" />
          History
        </Button>
      )}
    </div>
  );
};
